### ISSUE TITLE
Should IAsyncBuildTask be implemented with IEnumerator?

### ISSUE THREAD

**Issue by PavelKlym** [StansAssets/com.stansassets.build#37]
https://github.com/StansAssets/com.stansassets.build/blob/master/com.stansassets.build/BuildPipeline/Interfaces/Tasks/Async/IAsyncBuildTask.cs

Asking because:
1. Can't handle Exception properly
2. Can't pass any complete argument. For example we failed the Task, but the is no option to tell the system about that.

**Comment by aleh-patseyeu** [comment]
If we will stick with the Coroutines, here is a good overview of the possible solutions:
https://www.jacksondunstan.com/articles/3718

**Comment by aleh-patseyeu** [comment]
Async support will not be implemented (see #19)
