### ISSUE TITLE
Inconsistent name of the basic element across the project

### ISSUE THREAD

**Issue by aleh-patseyeu** [StansAssets/com.stansassets.build#39]
Codebase contains different names for the same thing:
- all essential building blocks have the `Task` postfix
- pipeline visualization use the name `step`
- some components use both variants for the variable/method names in the same context
https://github.com/StansAssets/com.stansassets.build/blob/master/com.stansassets.build/BuildPipeline/Core/BuildProcessor.cs#L67

I think we should unify the name in order to not introduce ambiguity out of nowhere for the package users and maintainers.

**Comment by PavelKlym** [comment]
Let's replace any Tasks mentions with "Step". It is the same thing :)
